# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(help_text='URL', unique=True, verbose_name='URL'),
        ),
    ]
