# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-02 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160102_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 1, 2, 22, 15, 22, 632117), help_text='URL', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
